import type { Metadata } from "next";
import { inter } from "./ui/fonts";
import "@/app/ui/globals.css";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className="h-full bg-white">
        <body className={`${inter.className} h-full`}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
